name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch:depth: 0
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secret.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secret.DOCKER_PASSWORD }} 
      run: |
        echo "Iniciando proceso de login"
        docker login -u $DOCKER_USER -p ${DOCKER_PASSWORD}
        echo "finalizado proceso de login"
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
